baseURL = "https://cminoldo.github.io/"
locale = "es-AR"
title = "Archivo periodistico - Claudio Minoldo"
theme = "ananke"
publishDir = "docs"

[params]
  description = "27 anos de cobertura periodistica en el norte de Cordoba (1996-2023)"
  author = "Claudio Minoldo"

[taxonomies]
  category = "categories"
  tag = "tags"

[markup.goldmark.renderer]
  unsafe = true